# Generated by Django 5.0.4 on 2024-06-10 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=32)),
                ('nombre_usuario', models.CharField(max_length=32)),
                ('clave', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialVentas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('responsable', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.usuario')),
                ('id_ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.historialventas')),
            ],
        ),
    ]
