# Generated by Django 5.0.4 on 2024-07-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialventas',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
